# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record',
            name='back_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8fd8\u4e66\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='borrow_record',
            name='borrow_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u501f\u4e66\u65f6\u95f4'),
        ),
    ]
