# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180206_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_user',
            name='wechat_openid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
