# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_borrow_user_wechat_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_user',
            name='wechat_openid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
