# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 11:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180212_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
