# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180212_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record',
            name='is_return',
            field=models.BooleanField(choices=[(True, '\u4f7f\u7528\u4e2d'), (False, '\u7a7a\u95f2')], default=False, verbose_name='\u662f\u5426\u5f52\u8fd8'),
        ),
    ]
